# Generated by Django 2.2.10 on 2021-02-28 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='Option',
            new_name='option',
        ),
    ]
