# Generated by Django 2.2.10 on 2021-02-28 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poll_app', '0003_auto_20210228_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='many_options',
            field=models.ManyToManyField(blank=True, null=True, to='poll_app.Option'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='one_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='option', to='poll_app.Option'),
        ),
    ]
