# Generated by Django 2.2.10 on 2021-02-28 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll_app', '0004_auto_20210228_1404'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='user',
        ),
        migrations.AddField(
            model_name='answer',
            name='anonymus',
            field=models.GenericIPAddressField(default='defaultuser'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='answer',
            name='text_input',
            field=models.TextField(blank=True, null=True),
        ),
    ]
